//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSqlWpfLogisticCompany.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appSqlWpfLogisticCompany.Properties.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string authorizationButtonSignIn {
            get {
                return ResourceManager.GetString("authorizationButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string authorizationButtonSignUp {
            get {
                return ResourceManager.GetString("authorizationButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АВТОРИЗАЦИЯ.
        /// </summary>
        public static string authorizationHeader {
            get {
                return ResourceManager.GetString("authorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МЫ РАДЫ ВИДЕТЬ ТЕБЯ.
        /// </summary>
        public static string authorizationLeftText1 {
            get {
                return ResourceManager.GetString("authorizationLeftText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станем лучшими в своем деле вместе с тобой.
        /// </summary>
        public static string authorizationLeftText2 {
            get {
                return ResourceManager.GetString("authorizationLeftText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта не указана.
        /// </summary>
        public static string emptyEmail {
            get {
                return ResourceManager.GetString("emptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин не указан.
        /// </summary>
        public static string emptyLogin {
            get {
                return ResourceManager.GetString("emptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не указан.
        /// </summary>
        public static string emptyPassword {
            get {
                return ResourceManager.GetString("emptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле электронной почты должно содержать по крайней мере один символ и @mail.ru на конце.
        /// </summary>
        public static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В пароле должна содержаться минимум одна заглавная буква.
        /// </summary>
        public static string errorPassword_MinCapitalLetter {
            get {
                return ResourceManager.GetString("errorPassword_MinCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В пароле должны содержаться минимум три строчных буквы.
        /// </summary>
        public static string errorPassword_MinLoweraseLetter {
            get {
                return ResourceManager.GetString("errorPassword_MinLoweraseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В пароле должны содержаться минимум две цифры.
        /// </summary>
        public static string errorPassword_MinNumber {
            get {
                return ResourceManager.GetString("errorPassword_MinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В пароле должен содержаться минимум один спец. символ.
        /// </summary>
        public static string errorPassword_MinSpecSymbols {
            get {
                return ResourceManager.GetString("errorPassword_MinSpecSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует.
        /// </summary>
        public static string existingUserLogin {
            get {
                return ResourceManager.GetString("existingUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с такой почтой уже существует.
        /// </summary>
        public static string existingUserMail {
            get {
                return ResourceManager.GetString("existingUserMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string languageEnglish {
            get {
                return ResourceManager.GetString("languageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string languageRussian {
            get {
                return ResourceManager.GetString("languageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string registrationButtonBack {
            get {
                return ResourceManager.GetString("registrationButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string registrationButtonRegistration {
            get {
                return ResourceManager.GetString("registrationButtonRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РЕГИСТРАЦИЯ.
        /// </summary>
        public static string registrationHeader {
            get {
                return ResourceManager.GetString("registrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта.
        /// </summary>
        public static string textEmail {
            get {
                return ResourceManager.GetString("textEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string textLogin {
            get {
                return ResourceManager.GetString("textLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string textPassword {
            get {
                return ResourceManager.GetString("textPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль.
        /// </summary>
        public static string wrongLoginPassword {
            get {
                return ResourceManager.GetString("wrongLoginPassword", resourceCulture);
            }
        }
    }
}
