//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSqlWpfLogisticCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Users_Photo = new HashSet<Users_Photo>();
        }
    
        public int Code_User { get; set; }
        public string Name_User { get; set; }
        public string Surname_User { get; set; }
        public string Midname_User { get; set; }
        public string Login_User { get; set; }
        public int Password_User { get; set; }
        public int Code_Gender { get; set; }
        public System.DateTime Date_Birthday_User { get; set; }
        public int Code_Role { get; set; }
        public string Mail_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Photo> Users_Photo { get; set; }
        public virtual Users_Gender Users_Gender { get; set; }
    }
}
