//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSqlWpfLogisticCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int Code_Vehicle { get; set; }
        public int Code_Executor { get; set; }
        public int Code_Category { get; set; }
        public string Brand_Vehicle { get; set; }
        public string Model_Vehicle { get; set; }
        public float Length_Vehicle { get; set; }
        public float Width_Vehicle { get; set; }
        public float Height_Vehicle { get; set; }
        public float Tonnage_Vehicle { get; set; }
        public float Volume_Vehicle { get; set; }
        public string Number_Vehicle { get; set; }
    
        public virtual Category_Trailer Category_Trailer { get; set; }
        public virtual Executors Executors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
